"""
KAIROS harness — post hoc slices of the baseline's 1X2 bets (hypotheses S3, S4, S5).

Walks the development data with B0 only and cuts its 1X2 bets by claimed edge,
league group, era and price taken. Descriptions, not tests: see the note in
research/hypotheses.md. Writes research/results/slices.json and slices.md and
appends one line per group to research/runs.jsonl.

CLI:  python harness/run_slices.py [--no-log]

Pure stdlib.
"""

from __future__ import annotations

import json
import os
import sys

import fd_data
import fd_fetch
import metrics
import runlog
import score
import strategies
import walk
from run_baseline import BET_HEAD, RESULTS_DIR, bet_row, ci, pct

BIG5 = {"E0", "SP1", "D1", "I1", "F1"}
FIRST_TIER = {"E0", "SC0", "D1", "I1", "SP1", "F1", "N1", "B1", "P1", "T1", "G1"}


def era(season: str) -> str:
    return "1213-1718" if fd_fetch.season_start_year(season) <= 2017 else "1819-2425"


def band(x: float, edges, labels) -> str:
    for e, lab in zip(edges, labels):
        if x < e:
            return lab
    return labels[-1]


SLICES = {
    "S3 claimed edge": lambda b: band(b["claimed_ev"], (0.05, 0.10, 0.15),
                                      ("3-5%", "5-10%", "10-15%", "15%+")),
    "S4a big five": lambda b: "E0 SP1 D1 I1 F1" if b["league"] in BIG5 else "other 17 leagues",
    "S4b tier": lambda b: "first tier" if b["league"] in FIRST_TIER else "lower tiers",
    "S4c era": lambda b: era(b["season"]),
    "S5 price taken": lambda b: band(b["odds"], (2.5, 5.0, 10.0),
                                     ("under 2.5", "2.5-5", "5-10", "10 and over")),
}
MATCH_GROUP = {
    "S4a big five": lambda p: "E0 SP1 D1 I1 F1" if p.league in BIG5 else "other 17 leagues",
    "S4b tier": lambda p: "first tier" if p.league in FIRST_TIER else "lower tiers",
    "S4c era": lambda p: era(p.season),
}


def main() -> None:
    matches = fd_data.load_development()
    b0 = strategies.KairosV2("B365", 0.03, markets=("1x2",))
    sc = score.Scorer()
    walk.run(matches, [b0], sc)
    bets = sc.bets[b0.name]
    priced = [p for p, _ in matches if "PS" in p.odds_1x2 and "B365" in p.odds_1x2]

    res: dict = {"commit": runlog.git_commit(), "bets": len(bets),
                 "priced_matches": len(priced),
                 "mean_claimed_ev": sum(b["claimed_ev"] for b in bets) / len(bets)}
    for name, key in SLICES.items():
        groups: dict = {}
        for b in bets:
            groups.setdefault(key(b), []).append(b)
        out = {}
        for g, bs in groups.items():
            s = metrics.bet_summary(bs)
            p = metrics.bet_summary([dict(b, clv=b["clv_prop"]) for b in bs])
            s["clv_prop"], s["clv_prop_ci"] = p["clv"], p["clv_ci"]
            s["mean_claimed_ev"] = sum(b["claimed_ev"] for b in bs) / len(bs)
            if name in MATCH_GROUP:
                n = sum(1 for m in priced if MATCH_GROUP[name](m) == g)
                s["priced_matches"], s["share_of_outcomes"] = n, len(bs) / (3 * n)
            out[g] = s
        res[name] = out

    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(os.path.join(RESULTS_DIR, "slices.json"), "w", encoding="utf-8") as f:
        json.dump(res, f, indent=1, sort_keys=True)

    L = ["# Post hoc slices of the baseline's 1X2 bets", "",
         f"Generated by `harness/run_slices.py` at commit `{res['commit']}`. {res['bets']} bets "
         f"from {res['priced_matches']} matches priced by both Pinnacle and Bet365. "
         f"Mean claimed edge {pct(res['mean_claimed_ev'])}. Descriptions, not tests.", ""]
    for name in SLICES:
        L += [f"## {name}", "", BET_HEAD[:BET_HEAD.index("\n")]
              + " CLV, proportional | Mean claimed edge | Share of outcomes |",
              "|---|---|---|---|---|---|---|---|---|---|"]
        for g, s in res[name].items():
            share = f"{s['share_of_outcomes'] * 100:.2f}%" if "share_of_outcomes" in s else "-"
            L.append(bet_row(g, s) + f" {pct(s['clv_prop'])} ({ci(s['clv_prop_ci'])}) | "
                     f"{pct(s['mean_claimed_ev'])} | {share} |")
        L.append("")
    with open(os.path.join(RESULTS_DIR, "slices.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("\n".join(L))

    if "--no-log" not in sys.argv:
        for name in SLICES:
            for g, s in res[name].items():
                runlog.append(name.split()[0][:2], f"{b0.name} 1x2 | {name} = {g}",
                              "development league-seasons only",
                              {k: s[k] for k in ("bets", "roi", "roi_ci", "clv", "clv_ci")})


if __name__ == "__main__":
    main()
